ALTER TABLE "groups" ADD COLUMN IF NOT EXISTS "inboundEmail" TEXT;
ALTER TABLE "groups" ADD COLUMN IF NOT EXISTS "latestOtp" TEXT;
ALTER TABLE "groups" ADD COLUMN IF NOT EXISTS "otpReceivedAt" TIMESTAMP(3);
ALTER TABLE "groups" ADD COLUMN IF NOT EXISTS "otpSubject" TEXT;
